apiVersion: v1
description: A Helm chart for TiDB Cluster
name: tidb-cluster
version: 1.0.3
home: https://github.com/pingcap/tidb-operator
sources:
  - https://github.com/pingcap/tidb-operator
keywords:
  - newsql
  - htap
  - database
  - mysql
  - raft
